[build]
  command = "npm run build && cd netlify/functions && npm install"
  functions = "netlify/functions"
  publish = "dist"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[functions]
  node_bundler = "esbuild"